name: Algolia
on:
  push:
    branches: main
    paths:
      - 'src/lib/transcriptions/*.json'
      - 'src/lib/transcriptions/index.js'
      - 'scripts/algolia-data.js'
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Repopulate Algolia
        run: npm run algolia
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
